### ISSUE TITLE
Make level-91 characters immune to hunger/thirst

### ISSUE THREAD

**Issue by prophnoran** [prophecymud/ideas#10]
It's fun to add a bit of challenge/realism when leveling (gotta stock up for your journey!) but just annoying at level 91.

**Comment by anhegofcherek** [comment]
Definitely agree on the annoyance front!

What I think I'd like to do is something like this:

* Reduce the penalties for being hungry/thirsty - no harm should come to you, but maybe natural regeneration is either slowed or non-existent
* Allow toggling whether you see hunger/thirst messages

That way:

1. You can ignore it if you like - if you're new or just not equipped to deal with it
2. There's still value in food, drink, quest jugs etc.

How's that sound?

**Comment by prophnoran** [comment]
I guess people would be annoyed if we devalued all their hard-earned quest jugs (but, that's a general question: are you willing to make changes like that, if it feels like it makes the game better?)

I think your suggestions are good. If able to turn off hunger/thirst it'd be good to have a way to have your hunger/thirst status appear in your prompt (if there's not one already!). Maybe I'm biased because I don't have a quest jug :).

One additional thing that reduces spam a lot is: if you have a quest jug in your inventory (including in a bag), you should just... not ever get hungry. No need for the whole room to see five lines of "Noran gets jug from bag; Noran drinks from jug x3; Noran puts jug in bag" every x minutes!

**Comment by anhegofcherek** [comment]
> are you willing to make changes like that, if it feels like it makes the game better?

Absolutely yes! But I'm also reluctant to rip out an entire mechanic if it can just be tweaked a little instead

**Comment by anhegofcherek** [comment]
@prophnoran How would you feel about closing this in favour of #51 ?

**Comment by anhegofcherek** [comment]
Since #51 is now live, I'm closing this - thanks for the input!
