### ISSUE TITLE
Drop skill customisation?

### ISSUE THREAD

**Issue by anhegofcherek** [prophecymud/ideas#109]
Mildly controversial idea I'm floating for discussion: I'd be quite tempted to drop skill customisation if I could see a good way

I suspect basically everyone adds approximately the same skills, e.g.:

> Looking at a knight for example, assuming you've added default. I expect everyone would add transportation and scry, nobody would add mount, basically nobody would add kick, most would add crit and fourth and riposte, then the rest are basically "pvp or not"

though knights are quite basic, but even sorcs:

> I bet ~everyone adds drac; most add most of shield block, dodge, enhanced, second, fast healing, meditation; with h2h/trip/sps if pvp; nobody takes scribe, virtually nobody takes brew

"Here are twenty levers with lasting consequences to your character, and almost everybody experienced pulls them in basically the same way" doesn't feel fun or interesting or rewarding

Now I don't actually think this specific change would be especially easy to get right, or particularly worthwhile, so I'm unlikely to actually do it any time, but I'd still be interested in people's thoughts here

**Comment by grekan** [comment]
I like pulling all the levers, the down side is for new players primarily.

I would just make sure default actually includes useful skills, even if that means raising the defaults to 2k instead of 1k. Also allow defaults to pull in other packages like transportation.

**Comment by anhegofcherek** [comment]
I forgot this existed when I created #116 but I think that's a better analysis and plan, so closing this in favour of it
