### ISSUE TITLE
astring reset

### ISSUE THREAD

**Issue by CorlanProphecy** [prophecymud/ideas#111]
Since restrung items now display what the original item was, can we get an option to "restring reset" to revert back to the old string and make identify no longer supply the original string. Either at a discount of 100 aqps or at the same price. In some instances the original string is preferred but astringing back to the old string would mean identify still supplies that the item is restrung, its a very subtle and mostly sub-cosmetic change but it would provide some neatness.

Also an option of string "history" would be exceptionally cool for mud archaeologists like myself. Many q-items have been around for long, i have no idea if this data is at all stored. But if it is, an option of "identify history" providing a list of old strings for the item would be really awesome.

**Comment by anhegofcherek** [comment]
> can we get an option to "restring reset"

Absolutely! Nice and easy to do

> Also an option of string "history" would be exceptionally cool for mud archaeologists like myself

I really like this! Alas it's trickier (I'm trying to avoid adding new information to be saved, because of how painful the current data formats are) but gosh I'd love that for the history

**Comment by anhegofcherek** [comment]
```
$ aq destring birthday
Your HAPPY BIRTHDAY ANHEG reverts to a a blank Quest Bag. 
```
