### ISSUE TITLE
Remove stat training

### ISSUE THREAD

**Issue by anhegofcherek** [prophecymud/ideas#117]
Thanks to @prophnoran for this

A current footgun is training stats - when the "optimal" build that experienced players know is to spend trains on hpmana

This is a one-way path for a character, the only way to undo it is to reroll

Thus a good quick fix is to remove the ability to train stats

This is simple, and I think it's uncontroversial; I'll likely do it soon when I get the chance if nobody comes up with good reasons not to!

**Comment by grekan** [comment]
I 100% support this. The system is clearly geared towards the idea of you training stats, which as you identify eventually results in that person rerolling. Not a fun time for anyone. Stats not impacting leveling gains only fixed half the footgun as you call it.

**Comment by grekan** [comment]
I just want to add, would it be possible to get rid of this in terms of training at trainers, but leave it possible to train via AQ?

**Comment by prophnoran** [comment]
AQ stat training seems not as much a footgun so I'd support keeping it.

A less drastic version is to level gate stat training, hopefully by the time a player is (say) level 75, someone will have told them about this.

**Comment by prophnoran** [comment]
PS, I didn't even know you could AQ train! https://github.com/prophecymud/prophecy-issues/issues/22

**Comment by anhegofcherek** [comment]
> I just want to add, would it be possible to get rid of this in terms of training at trainers, but leave it possible to train via AQ?

Absolutely yes - my only target here is regular `train` because trains are limited

**Comment by anhegofcherek** [comment]
This is merged and should go live in the next deployment, thanks all
