### ISSUE TITLE
Channel histories

### ISSUE THREAD

**Issue by prophnoran** [prophecymud/ideas#15]
To make conversation easier, it'd be cool to be able to see recent (up to a day, say) things said on ooc etc.

**Comment by prophnoran** [comment]
Related to #5

**Comment by anhegofcherek** [comment]
Neat idea, thanks! Much easier than #5 too!

**Comment by prophnoran** [comment]
If ooc et al become, in this way, more like persistent chatrooms (a la slack) then implementing @mentions seems cool:

If you're online, it draws your attention by making the channel a different color

When you log in, if you've been mentioned thus recently, you get a notification (like unread notes)

**Comment by anhegofcherek** [comment]
Thanks for this @prophnoran - apologies I failed to remember that you'd already posted it when I wrote #36!

I'm going to close this on the same basis as #36 - `oocbuffer` exists - could I ask that you sketch out the mentions idea in its own issue if you're still keen please, and we use #62 for discussion around what channels are included - thanks
