### ISSUE TITLE
ooc history

### ISSUE THREAD

**Issue by anhegofcherek** [prophecymud/ideas#36]
It'd be nice to see recent chatter on ooc when you login. Technically this shouldn't be too hard.

The challenging part is probably "what to do about player visibility" - when a player (mortal or immortal) is invisible. I don't really want to have to store anything more than their name.

An easy way to sidestep that entirely is to make history be immortal-only (since we can see everyone) I suspect others would be keen for the functionality too though!

One way to deal with the mortal issue would be to have mortal names always visible on ooc - it _is_ `out of character` after all.

At that point, maybe it would be enough? Store the message, the player name, and any imm-level invisibility (for imms), then show all names to imms, and `An Immortal` for mortals looking at historic message from invisible imms.

I'm open to variant ideas though!

**Comment by Ranfir** [comment]
Shouldn't it be easy enough to log the visibility status of imms, and then apply the appropriate filter?

For mortals, I don't think it should be a big deal. The only concern I can think of is around PK, but if a PKer is trying to hide their visibility, you'd think they'd also stay off of ooc.

**Comment by grekan** [comment]
I agree with @Ranfir ooc not considering sneak/hidden/invis (imms excluded) would probably actually enhance ooc's usefulness and also allow you to implement this as described.

**Comment by prophnoran** [comment]
See #15 :).

I agree with @grekan and @Ranfir : it's an improvement for ooc to not take sneak/hidden/invis into account. I'd go even further and say that you should still show up on `who` in these circumstances unless you are PK.

**Comment by anhegofcherek** [comment]
> See #15 :).

I thought this felt familiar - thanks!

**Comment by anhegofcherek** [comment]
On my dev port (:4005) is an experimental version - it doesn't handle visibility but otherwise should be fine - thoughts?

```
$ oocbuffer
Recent OOCs (10):
====================

Jan 12 02:30:26: Anheg oocs 'f'
[etc.]
```

**Comment by grekan** [comment]
I like it, works well. Could we up the buffer a bit? Maybe 20?

**Comment by grekan** [comment]
I vote we implement it if it's ready.

**Comment by anhegofcherek** [comment]
I've upped it to 25 and added handling for hidden immortals

**Comment by kerowa** [comment]
I like this idea!

**Comment by anhegofcherek** [comment]
And it's in - thanks all!
