### ISSUE TITLE
Impressions from watching over a newbie's shoulder

### ISSUE THREAD

**Issue by prophnoran** [prophecymud/ideas#37]
1) The first time I tried to get my friend to play he got very intimidated by the wall of rules about names and gave up

2) Names are a big sticking point; I sort of think the rules are too strict ATM

3) In mudschool, leading with the introduction to the world is not what he wanted. He doesn't care about what a Drasnian is, he wants to know how to move around the game

4) Re: hunger, "soft butterfly wings? do they have chicken wings?"

5) "You're thirsty?! Oh come on!" ... "can I drink the butterfly wing?"

6) `drink waterskin` -> `You can't find it` -> "... what?"

7) (some time later) "I'm hungry again. This is annoying."

8) `consider` doesn't really work, was more confusing than anything.

9) "My 'grep'? What does 'grep' mean?" (re: damnoun)

Concrete suggestions:

1) Really rethink names
1a) Some of the rules might be too strict. Is it going to break your immersion if it turns out the thing has a few more google hits? If it's the name of a hardware store in Brazil?
1b) Shorten the big long list of names rules and make it less yell-ish. How about something like

> In choosing a name, remember this is a role-playing game, so please choose appropriately: please avoid English words, or names from fiction (especially the Eddings novels on which this game is based!)

1c) Maybe we could have a big list of preapproved names; using one of these can avoid the validation process altogether. Offer it up at the 'is that really your name?' prompt.

2) Fix `consider`; there are two problems:
2a) Whatever heuristic it is using doesn't have much bearing on whether or not you can actually kill the mob.
2b) Many of the strings are ambiguous: "Death will thank you for your gift" -> your gift of whose death, the player's or the mob's? Or else are weird stilted language ("A little work for lots of blood cleansing" or whatever it is). This is especially challenging for non-native English speakers (such as my friend)

3) Rethink hunger (but there's already an open issue for this, #10 , although that one is phrased to be more specific)

4) `drink` should, like `eat`, say `You don't have that item`. Even better they should both say `You don't have an item called <x>`. 
4a) The newbie waterskin should have `waterskin` as a name(!)

5) Change `grep` to something else, maybe `blow` or `strike`

**Comment by anhegofcherek** [comment]
Thanks - I appreciate you collecting this up!

I also appreciate you splitting it out into separate threads - ok to close this in favour of them?

**Comment by prophnoran** [comment]
SGTM
