### ISSUE TITLE
`consider` redesign

### ISSUE THREAD

**Issue by prophnoran** [prophecymud/ideas#38]
See #37 .

One possibility: `consider` can say something like:

`consider Noran` prints 4 lines. They are:

`It looks like Noran's armor is better than yours!` or `It looks like your armor is stronger than Noran's`
`It looks like Noran hits harder than you!` or `It looks like you hit harder than Noran!`
`It looks like Noran is healthier than you!` or `It looks like you are healthier than Noran!`
`All in all, it looks like a fair fight` or `All in all, Noran would probably win!` or `All in all, you think you can take him!`

The first 3 are based on a straight comparison of AC, H/D, and HP; the last is based on a better heuristic (needs fine-tuning) than currently there. At the very least, it should work well for mobs in mud school / in the early leveling areas.

**Comment by anhegofcherek** [comment]
Definitely agree it needs improvement

I suspect it's going to be complex to get "right", even with simple straight comparisons, because of the PC/NPC differences

Still, this would be a significant improvement over what we have now (level difference) - thanks

**Comment by anhegofcherek** [comment]
Trying to do a comparison, or meaningful values for PCs, is hard - I spent a while at it and didn’t make much progress

But today I’ve pushed two improvements

First, “Death will thank you for your gift” was horribly unclear - were you the gift or were they? This message is now clearer…!

Second,  `consider`ing a mob now shows some indication of their HP, AC, and damage.

They aren’t relative, they aren’t especially sophisticated, and there’s definitely need for further improvement. But what I’ve also added is a display of the raw data for immortals (or builders on BP) so it’s easier to further refine for the future.

Lots of the relevant combat calculations are complex and intertwined with existing things which doesn’t help, but also there’s so very many factors involved. I think I’d rather a crude system that was always relatively accurate than a complex system that could be misleading…

I’m going to close this on the basis that `consider` is substantively improved right now but I don’t mean to dismiss the underlying point - I think it could be well worth talking about refinements or different ideas etc in a follow up thread if that seems reasonable?
