### ISSUE TITLE
Equipped stats not affecting levelling gains

### ISSUE THREAD

**Issue by anhegofcherek** [prophecymud/ideas#4]
Right now the amount of hp/mana/practices/trains you get upon gaining a level are affected by your stats (int, wis etc.)

This means that choices you make while new / starting a character can end up permanently "negatively" affecting you, and selecting eq while levelling is a careful exercise in making sure everything is maxed.

This doesn't feel fun.

Long-term I'd like to increase the impact of _current_ stats (e.g. strength indirectly adding to damage in a meaningful way) to make them matter more at 91

Short-term, making levelling gains unaffected by stats (and as though you levelled with max stats under the current/"previous" system) feels like it'll help here - especially for any new players

**Comment by prophnoran** [comment]
This is great. I think also getting rid of practices-to-trains would be good too: at the moment, the best way to make a character is to bot everything, so you get that last bit of HP/mana/whatever.

Botting doesn't feel fun.

Instead, get rid of the conversion so that pracs can only be used for improving skills, and grant players an equivalent number of trains on level up.

**Comment by anhegofcherek** [comment]
Agreed - that definitely requires a bit more balancing thought though!

**Comment by prophnoran** [comment]
Can you say more about the balance issues? I moved it to #43, as its a separate issue from stats.

**Comment by anhegofcherek** [comment]
> Can you say more about the balance issues? I moved it to #43, as its a separate issue from stats.

I think I just didn't fully appreciate the entire last sentence - removing convert while giving people equivalent extra trains should be fine (it'd take some work to determine when/how to give them the trains, but it's doable) - thanks!

**Comment by anhegofcherek** [comment]
I realised the other day when I threw together a prototype:

It's not "*stats* not affecting levelling gains", it's "equipment" - your _maximum_ stats still affect your gains, but they're solely a function of your race and class, and nothing to do with your equipment.

**Comment by anhegofcherek** [comment]
So I have this ready to go live, subject to two considerations:

First, it could use a bit of testing, but this should be easy and straightforward

Second, I don't want it to suddenly just reshape the current problem. Outside of levelling gains, stats don't have a huge amount of meaningful effect. One of the goals of doing this was to provide more variety in what people wear. I don't want it to suddenly become "instead of everyone wearing the max stats set, they now wear the max hitdam set".

Now:

* I don't _think_ that's necessarily what would happen
* I think it's still a worthwhile tradeoff - removing the "oops I wasn't wearing the perfect set and am forever harmed" effect
* It still means more variety as people can switch out things as they like/need/find them

but still I think I'd like to at least kick around some ideas about making stats have more of a real-time impact first - even if it's just relatively crude dex/AC, str/damage, etc. bonuses. Thoughts?

**Comment by anhegofcherek** [comment]
Interesting to note that for some test mortals:

* 91 caster equipment left them "missing" 1 int, 7 wis, 4 dex
* 91 evil warrior eq: 9 int, 7 wis, 3 dex, 5 con

At a glance:

* Int affects brew, practice gains, peek, sap resistance, scribe, fear, chance to improve at skills, chance to see someone sneaking, flurry amount, mana regeneration, mana gain
* Con helps not be sapped, a bit of spellsurge and energy channel, the amount of hp you regen, the amount of hp you gain

I think I want to raise the visibility and awareness of what stats do (and look at the eq on some of my mortals!)

**Comment by grekan** [comment]
Does dexterity not heavily impact AC?

**Comment by anhegofcherek** [comment]
* Dex affects sweep success, shove success, bash success, move gains, stun chance, AC, tackle chance, trip chance, dodge chance, riposte chance, diminish chance, shieldcharge chance, web evasion, heat metal avoidance, crush chance, sneak visibility, carry capacity, capture chance, fury chance, move regen, dirt chance, and disarm chance...

Gosh that's quite a bit!

And wow, -120 AC for 25 dex, -50 for 20...

@grekan Thanks for the prompt to check - I hadn't really realised just how much of a difference it made!

**Comment by Ssolvarain** [comment]
May want to consider running some math on what max HP would be with practices converted to trains, and compare that with a nice spread of characters. If botting skills, and converting trains was the norm, you'd want to find some kind of common ground to aim for as far as where you'd want the player's HP to wind up. This assumes you'd remove the option to train HP/MP, cap the maximum stats you could train vs. maximum a stat could possibly with outside modifiers, and deal with the issue of practices/trains that would wind up accumulating beyond what's actually able to be used.

If CON also had an influence on max HP on top of "normalized" gains, and WIS doing the same with mana, it'd give them a certain degree of usefulness. One option is having them act as a percentage of what amount of your total maximum vs. current maximum hp, with a max 25 score providing 100% and races with a less than a 25 max score possible simply rolling with the a less than 100% modifier.

If it were an ideal situation with the game just beginning, you could increase the maximum of core stats to a higher number for greater granularity, and adjusting/creating gear to accommodate increased stats. As things stand, you'd have to spend quite a bit of time either hand-adjusting equipment, or write a script to modify .are files, and wind up with likely inflexible results.

Just some thoughts.

**Comment by anhegofcherek** [comment]
> May want to consider running some math on what max HP would be with practices converted to trains

Thanks; I'd like to keep this issue focussed on equipped stats not affecting levelling gains (as per title) - you might be looking for @prophnoran 's #43 or similar

**Comment by anhegofcherek** [comment]
> Second, I don't want it to suddenly just reshape the current problem. Outside of levelling gains, stats don't have a huge amount of meaningful effect. One of the goals of doing this was to provide more variety in what people wear. I don't want it to suddenly become "instead of everyone wearing the max stats set, they now wear the max hitdam set".

I thought about this a bit more

It won't make a difference at 91 - they've no levelling to do

So the only consequences will be on people levelling

What's the effect? Well maybe they'll hyper-optimise on "the max hitdam set":

* Above has shown it's not actually clear whether that should be the main focus even with the current system (maybe some dex is worthwhile for the AC, or int for the skill improvement chance etc.)
* Even if they do, they've got more freedom to change things up, because they don't "need" to keep stats maxed, and there's no lasting "penalty" for wearing suboptimal kit

Thus I think it's a net improvement, even without increasing the real-time impact of stats, so I think I'll merge this later on in the week, barring objection

**Comment by grekan** [comment]
I welcome the change, and agree that given stats are impactful in other ways, it won't be a race for just h/d eq. 

It might be nice to eventually have a listing of what stats actually impact somewhere. The amount of things dex alone impacts is astounding.

**Comment by prophnoran** [comment]
> Thus I think it's a net improvement, even without increasing the real-time impact of stats, so I think I'll merge this later on in the week, barring objection

I agree with this analysis. Looking forward to the change :).

**Comment by anhegofcherek** [comment]
And it's live! Enjoy :)
