### ISSUE TITLE
`drink` error message can be more clear

### ISSUE THREAD

**Issue by prophnoran** [prophecymud/ideas#42]
See #37.

How about `You don't have an object called **waterskin**` instead of `You can't find it`

**Comment by anhegofcherek** [comment]
Definitely - *so* many places in the code could do with more helpful "error" messages!

**Comment by anhegofcherek** [comment]
Fixed in next deploy, thanks!

Drink will:

* Show the text you supplied if it can't find an object
* Show the short description of an object if you can't drink from it
* Show the short description of an object if it's empty
