### ISSUE TITLE
Basic Hometown system

### ISSUE THREAD

**Issue by anhegofcherek** [prophecymud/ideas#48]
Currently we have the start of a "hometown" system:

* A hometown is a name, a `recall` vnum, and a `death` vnum
* You choose a hometown at creation
* There's only one hometown - Sendar

I think there'd need to be quite a bit of work to make there be other hometowns that were viable *starting* choices - ensuring there were decent levelling areas, routes out, and other facilities etc.

*However* I think we could get partway there by starting everyone off in Sendar, but letting people `migrate` to a different hometown at the relevant healer.

For example, go to Sthiss Tor, find Zekk, and `migrate`, then future `recall`s and deaths leave you at the Sthiss Tor Town Square.

I'm not sure it adds a huge amount, and I'm slightly conscious of the balance effects for PvP, but I think it could be fun and should be fairly straightforward

**Comment by anhegofcherek** [comment]
I'd like to pull together some initial hometown ideas.

Criteria:

* Needs a healer
* Should have "facilities" - trainer, shops, fountain, etc.
* Needs to be relatively safe - Mal Yaska, being full of demons, isn't appropriate

Let's initially aim for ~one per race as a guiding constraint.

As per OP, I'm not expecting these to be viable _starting_ hometowns yet, but it would be good to have that in mind. For them to actually be starting hometowns would require answering some nontrivial questions like how to handle mudschool, directions, location, etc.

Initial thoughts:

* Sthiss Tor
* Rak Urga
* Tol Honeth

**Comment by grekan** [comment]
I don't want to just migrate and have to load in a specific room in the center of a city. It would be even cooler if you could just reassign where word of recall deposits you. Maybe for a small fee. 

Ex. I'm in a room I want to be my new recall (private rooms or no gate rooms etc would be a no) and I set migrate and boom that's recall. Tomorrow I change it because it's not useful anymore etc. 

Perhaps 5-10k for the change?

**Comment by anhegofcherek** [comment]
> It would be even cooler if you could just reassign where word of recall deposits you

At that point it becomes a bit too much like gate for my liking (transport to semi-arbitrary locations) and cuts out some of the potential differentiation of hometowns. I'm not sure I see the value

**Comment by grekan** [comment]
> > It would be even cooler if you could just reassign where word of recall deposits you
> 
> At that point it becomes a bit too much like gate for my liking (transport to semi-arbitrary locations) and cuts out some of the potential differentiation of hometowns. I'm not sure I see the value

Alright, well riffing on the idea, what if we could set the entry point of any area as recall. I'm thinking what if I want recall to not be a city, what if I'm more of a rural kind of guy?

**Comment by anhegofcherek** [comment]
> I'm thinking what if I want recall to not be a city, what if I'm more of a rural kind of guy?

I don't see why a "hometown" should _have_ to be a "city"...

**Comment by anhegofcherek** [comment]
Right, I've got the basics of this in, just need to sort `migrate`

I'm thinking the following criteria for hometowns:

* Recall and healer should be next to each other
* Both rooms should be gateable
* Healer should be safe
* Recall should not be safe
* Both rooms should be relatively accessible (so Tol Honeth, where the healer is behind a guard that charges 100 gold, is not)

I also think that maybe everyone should have Sendar as a hometown during quests/scrims, at least until we've played with it a bit more

**Comment by anhegofcherek** [comment]
Alright, a first version is coming on next deploy!

**Comment by anhegofcherek** [comment]
And it's in; followup in other threads please
