### ISSUE TITLE
Hunger/Thirst-free rooms

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/ideas#50]
Make certain rooms (maybe all safe rooms) such that hunger/thirst counters don't tick.

**Comment by anhegofcherek** [comment]
Hm. This is definitely less work than #51 but I'm conscious it doesn't benefit new players that much - it's great for all of us at 91, hanging out at healer or in a hall or somewhere, and it's definitely easy to do - but #51 makes life better for the newbie out levelling or exploring too, and I think I like that more

**Comment by anhegofcherek** [comment]
...I also forgot to mention that we have the `nostatus` flag which (can) accomplish this

**Comment by anhegofcherek** [comment]
Between `nostatus` and #51, I think we're good, but do please reopen and comment if I've missed anything - thanks!
