### ISSUE TITLE
Make managing hunger/thirst be a bonus, and remove penalties / annoyances

### ISSUE THREAD

**Issue by anhegofcherek** [prophecymud/ideas#51]
As per #10 - I don't want to get rid of hunger/thirst - I don't want to make food, fountains, quest jugs etc. worthless and pointless - BUT I don't want it to be an annoyance.

What I like is the idea of a system that you can _totally ignore_ if you want to, and that's fine, BUT if you deal with it and manage it, then you benefit.

That way if you're new, if you're on a phone or something, whatever inconveniences, it doesn't cause you problems and spam, BUT if you're an experienced player, you can benefit by addressing things.

What I think I'd like to do is something like this:

1. Reduce the penalties for being hungry/thirsty - no harm should come to you, but maybe natural regeneration is slowed
2. Allow toggling whether you see hunger/thirst messages

That way:

* You can ignore it if you like - if you're new or just not equipped to deal with it
* There's still value in food, drink, quest jugs etc.

How's that sound?

**Comment by Ranfir** [comment]
What are your thoughts on #50 as an alternative?

**Comment by Ranfir** [comment]
I see the appeal of your idea. How about have the hunger / thirst message fire once when the player becomes hungry/thirsty?

Additionally, have the player's hunger/thirst status appear under the **affects** command instead of a nag message each tick, like so:
```
You are affected by the following spells:
Spell: detect magic   : modifies none by 0 for 44 hours
Spell: detect hidden  : modifies none by 0 for 44 hours
Spell: detect invis   : modifies none by 0 for 44 hours
Spell: fly            : modifies none by 0 permanently

You are affected by the following conditions:
Hunger: reduces health regeneration by 50%.
Thirst: reduces health regeneration by 50%.
```

**Comment by grekan** [comment]
> 
> 
> I see the appeal of your idea. How about have the hunger / thirst message fire once when the player becomes hungry/thirsty?
> 
> Additionally, have the player's hunger/thirst status appear under the **affects** command instead of a nag message each tick, like so:
> 
> ```
> You are affected by the following spells:
> Spell: detect magic   : modifies none by 0 for 44 hours
> Spell: detect hidden  : modifies none by 0 for 44 hours
> Spell: detect invis   : modifies none by 0 for 44 hours
> Spell: fly            : modifies none by 0 permanently
> 
> You are affected by the following conditions:
> Hunger: reduces health regeneration by 50%.
> Thirst: reduces health regeneration by 50%.
> ```

I love this idea.

**Comment by anhegofcherek** [comment]
> Additionally, have the player's hunger/thirst status appear under the affects command

It already appears in `score` - why move it?

**Comment by prophnoran** [comment]
> It already appears in `score` - why move it?

I like the idea of putting it in `affects`: I almost never use `score`, and hunger/thirst feels like it fits in with other stuff in aff.

Perhaps also it could be added as a prompt flag :).

**Comment by anhegofcherek** [comment]
The original idea as posted is now (basically) a thing thanks to `metabolism` and removal of hunger/thirst damage

Could y'all migrate discussion about changes to how it's displayed to their own thread(s) as you feel appropriate please?
