### ISSUE TITLE
Enabling GA (prerequisite to listing Prophecy on Mudlet's default profiles)

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/ideas#78]
This is one of the requirements to getting Prophecy listed on Mudlet as a default profile that goes out to all Mudlet users.

> Ensure your MUD enables GA by default for Mudlet players - this means that the N: field bottom-right will be filled in with a number. This is important because a very useful function for making Mudlet scripts, isPrompt(), relies on that working.
Send IAC GA at the end of every prompt to do this.

https://wiki.mudlet.org/w/Listing_Your_MUD

**Comment by anhegofcherek** [comment]
Interesting - we'll send `GA` to players with `COMM_TELNET_GA` set...there's just no way for players to set that themselves!

In 2020 I'm tempted to just enable it for everyone rather than adding an extra config option...

**Comment by anhegofcherek** [comment]
My dev instance (:4005) should now always be sending it - if you'd like to test it out - it certainly helps with prompt checks in the clients I use!

**Comment by Ranfir** [comment]
This seemed to work fine for me in Mudlet.

**Comment by anhegofcherek** [comment]
Will go live on next deploy, thanks!

**Comment by prophnoran** [comment]
I think this is messing up rendering on Mukluk

![Screenshot_20200223-100611](https://user-images.githubusercontent.com/57878346/75114496-539f9480-5624-11ea-8735-399d9e54dce5.png)

**Comment by prophnoran** [comment]
Note the two weirdly rendered characters after each prompt. (The colors being wrong is a /different/ mukluk big which I believe has nothing to do with prophecy)
