### ISSUE TITLE
In-game map visualisation

### ISSUE THREAD

**Issue by anhegofcherek** [prophecymud/ideas#86]
```
$ goto Toth
The Temple of UL
[Exits: north south up]
     A huge billboard broadcasts some current events of the local society.
(White Aura) Toth is here, waiting to dispense some justice.

$ map 3

        *-   
        |    
*-*-   -*-*-*
|           |
*     *     *
|     | |   |
*)*-S O(*-*-*
|   | |   |
* S *-*-*-S *
| | , | , , |
*-*-*-*-*-*-*
/ / / | | | |
*-*-*-*)S *)*
```

Thoughts?

Alas no colours here, but this is a common snippet that's been around for a while - the `O` is me, the `S` is a shop, `)(,/` signify exits that don't go to the room as drawn (e.g. where going `nesw` wouldn't leave you in the same room)

**Comment by anhegofcherek** [comment]
I'm conscious there's a breadth in what people mean when they talk about mapping.

I'm proposing as a first step, something fairly simple like the above, which while basic, still gives you a better idea of your options and/or location, especially somewhere like Rak Cthol

I think there's something pretty incredible about the amount of people who could, e.g., run around Cthol and Kahsha comfortably in PvP - I think this will still preserve the value in that skill, while possibly making it more accessible (I acknowledge there might not be much worth in preserving that value nowadays...)

**Comment by grekan** [comment]
I think it would be a valuable tool. As we've discussed previously on the mud, this feature used to be available to mortals. As someone who doesn't map with their client, being able to have a sense of an area's layout would be useful especially at a glance. I know many areas, mentally, but over time they often blend together, a basic map would be helpful to jog the memory. 

Would these maps be built in, or we map areas and then type map to see them?

**Comment by prophnoran** [comment]
I like the idea broadly... these are a little hard to read, though :).

It might be fun to show you only rooms you've been in (recently), plus show where unexplored exits are.

**Comment by anhegofcherek** [comment]
> these are a little hard to read, though :)

In hindsight the example I picked wasn't great - the renderer is much nicer when "one move is one map unit" though, e.g. Rak Urga:

```
$ look
The Bank of Rak Urga
  You stand within a room where security is the most important thing, and
this is very visual upon your entrance.  Armed men stand in small groups
with their weapons drawn.  If you had any idea in your mind of robbing this
place you had better forget it now and save yourself all the trouble it
would cause.  The front of the bank leads to the main street just west of
here.  

[Exits: west]
A bored banker waits on you.
Rotho the money changer sits in the corner.

$ map 3

S-*-*-S      
  | |        
S-*-*-S   * *
  | |     | |
*-*-*-*-*-*-*
  | |     | |
*-*-*-O   * *
  | |        
*-*-*-*-*-*-*
| | | | | | |
*-*-*-*-*-*-*
  | |        
  *-*        
```

**Comment by anhegofcherek** [comment]
> Would these maps be built in, or we map areas and then type map to see them?

Moderate preference for "you see everything" because then I don't need to add in logic to track "exploration" ;P

**Comment by grekan** [comment]
> 
> 
> > Would these maps be built in, or we map areas and then type map to see them?
> 
> Moderate preference for "you see everything" because then I don't need to add in logic to track "exploration" ;P

That's kind of neat, for some reason I recall it was generated as you go back in the day. Maybe that's why it was removed? 

Would hidden exists show up?

**Comment by prophnoran** [comment]
Tracking which rooms you've been in does sound hard but also has nice impacts for https://github.com/prophecymud/ideas/issues/21 :)

**Comment by anhegofcherek** [comment]
And this is now live, enjoy!
