### ISSUE TITLE
AQ Modify Normal EQ

### ISSUE THREAD

**Issue by grekan** [prophecymud/ideas#97]
I'd love it if we could AQ remove some flags from non aq eq. 

I'm thinking AQ remove:
Melt-drop
rot-death
two handed
anti-align

Make it worth it, but also expensive, maybe 5k aqpts per flag?

**Comment by anhegofcherek** [comment]
Aqeq aside, aqp modifications to eq will only ever be cosmetic; if you want to enhance other eq, that's where qp come in

(I can see an argument for generally looking at melt_drop, but that's another discussion)
